/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAcademicYearsRouteImport } from './routes/_authenticated/admin.academic-years'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin.classes'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin.fees'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminSchoolsRouteImport } from './routes/_authenticated/admin.schools'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin.subjects'
import { Route as AuthenticatedAdminTermsRouteImport } from './routes/_authenticated/admin.terms'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedParentIndexRouteImport } from './routes/_authenticated/parent.index'
import { Route as AuthenticatedParentAnnouncementsRouteImport } from './routes/_authenticated/parent.announcements'
import { Route as AuthenticatedParentChildrenRouteImport } from './routes/_authenticated/parent.children'
import { Route as AuthenticatedParentFeesRouteImport } from './routes/_authenticated/parent.fees'
import { Route as AuthenticatedRankingsClassIdRouteImport } from './routes/_authenticated/rankings.$classId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedStudentAssignmentsRouteImport } from './routes/_authenticated/student.assignments'
import { Route as AuthenticatedStudentClassesRouteImport } from './routes/_authenticated/student.classes'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherAnnouncementsRouteImport } from './routes/_authenticated/teacher.announcements'
import { Route as AuthenticatedTeacherAssessmentsRouteImport } from './routes/_authenticated/teacher.assessments'
import { Route as AuthenticatedTeacherClassesRouteImport } from './routes/_authenticated/teacher.classes'
import { Route as AuthenticatedTeacherEventsRouteImport } from './routes/_authenticated/teacher.events'
import { Route as AuthenticatedTeacherMeetingsRouteImport } from './routes/_authenticated/teacher.meetings'
import { Route as AuthenticatedParentChildrenStudentIdRouteImport } from './routes/_authenticated/parent.children.$studentId'
import { Route as AuthenticatedStudentAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/student.assignments.$assignmentId'
import { Route as AuthenticatedTeacherAssessmentsAssessmentIdRouteImport } from './routes/_authenticated/teacher.assessments.$assessmentId'
import { Route as AuthenticatedTeacherAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/teacher.assignments.$assignmentId'
import { Route as AuthenticatedTeacherClassesClassIdRouteImport } from './routes/_authenticated/teacher.classes.$classId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAcademicYearsRoute =
  AuthenticatedAdminAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSchoolsRoute =
  AuthenticatedAdminSchoolsRouteImport.update({
    id: '/schools',
    path: '/schools',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTermsRoute = AuthenticatedAdminTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedParentIndexRoute =
  AuthenticatedParentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentAnnouncementsRoute =
  AuthenticatedParentAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentChildrenRoute =
  AuthenticatedParentChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentFeesRoute = AuthenticatedParentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedParentRoute,
} as any)
const AuthenticatedRankingsClassIdRoute =
  AuthenticatedRankingsClassIdRouteImport.update({
    id: '/rankings/$classId',
    path: '/rankings/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentAssignmentsRoute =
  AuthenticatedStudentAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentClassesRoute =
  AuthenticatedStudentClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherAnnouncementsRoute =
  AuthenticatedTeacherAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherAssessmentsRoute =
  AuthenticatedTeacherAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherClassesRoute =
  AuthenticatedTeacherClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherEventsRoute =
  AuthenticatedTeacherEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherMeetingsRoute =
  AuthenticatedTeacherMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedParentChildrenStudentIdRoute =
  AuthenticatedParentChildrenStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedParentChildrenRoute,
  } as any)
const AuthenticatedStudentAssignmentsAssignmentIdRoute =
  AuthenticatedStudentAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => AuthenticatedStudentAssignmentsRoute,
  } as any)
const AuthenticatedTeacherAssessmentsAssessmentIdRoute =
  AuthenticatedTeacherAssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => AuthenticatedTeacherAssessmentsRoute,
  } as any)
const AuthenticatedTeacherAssignmentsAssignmentIdRoute =
  AuthenticatedTeacherAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherClassesClassIdRoute =
  AuthenticatedTeacherClassesClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => AuthenticatedTeacherClassesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/academic-years': typeof AuthenticatedAdminAcademicYearsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/terms': typeof AuthenticatedAdminTermsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/announcements': typeof AuthenticatedParentAnnouncementsRoute
  '/parent/children': typeof AuthenticatedParentChildrenRouteWithChildren
  '/parent/fees': typeof AuthenticatedParentFeesRoute
  '/rankings/$classId': typeof AuthenticatedRankingsClassIdRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsRouteWithChildren
  '/student/classes': typeof AuthenticatedStudentClassesRoute
  '/teacher/announcements': typeof AuthenticatedTeacherAnnouncementsRoute
  '/teacher/assessments': typeof AuthenticatedTeacherAssessmentsRouteWithChildren
  '/teacher/classes': typeof AuthenticatedTeacherClassesRouteWithChildren
  '/teacher/events': typeof AuthenticatedTeacherEventsRoute
  '/teacher/meetings': typeof AuthenticatedTeacherMeetingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/parent/': typeof AuthenticatedParentIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/parent/children/$studentId': typeof AuthenticatedParentChildrenStudentIdRoute
  '/student/assignments/$assignmentId': typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
  '/teacher/assessments/$assessmentId': typeof AuthenticatedTeacherAssessmentsAssessmentIdRoute
  '/teacher/assignments/$assignmentId': typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
  '/teacher/classes/$classId': typeof AuthenticatedTeacherClassesClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/admin/academic-years': typeof AuthenticatedAdminAcademicYearsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/terms': typeof AuthenticatedAdminTermsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/announcements': typeof AuthenticatedParentAnnouncementsRoute
  '/parent/children': typeof AuthenticatedParentChildrenRouteWithChildren
  '/parent/fees': typeof AuthenticatedParentFeesRoute
  '/rankings/$classId': typeof AuthenticatedRankingsClassIdRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsRouteWithChildren
  '/student/classes': typeof AuthenticatedStudentClassesRoute
  '/teacher/announcements': typeof AuthenticatedTeacherAnnouncementsRoute
  '/teacher/assessments': typeof AuthenticatedTeacherAssessmentsRouteWithChildren
  '/teacher/classes': typeof AuthenticatedTeacherClassesRouteWithChildren
  '/teacher/events': typeof AuthenticatedTeacherEventsRoute
  '/teacher/meetings': typeof AuthenticatedTeacherMeetingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/parent': typeof AuthenticatedParentIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/parent/children/$studentId': typeof AuthenticatedParentChildrenStudentIdRoute
  '/student/assignments/$assignmentId': typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
  '/teacher/assessments/$assessmentId': typeof AuthenticatedTeacherAssessmentsAssessmentIdRoute
  '/teacher/assignments/$assignmentId': typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
  '/teacher/classes/$classId': typeof AuthenticatedTeacherClassesClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/admin/academic-years': typeof AuthenticatedAdminAcademicYearsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/terms': typeof AuthenticatedAdminTermsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/parent/announcements': typeof AuthenticatedParentAnnouncementsRoute
  '/_authenticated/parent/children': typeof AuthenticatedParentChildrenRouteWithChildren
  '/_authenticated/parent/fees': typeof AuthenticatedParentFeesRoute
  '/_authenticated/rankings/$classId': typeof AuthenticatedRankingsClassIdRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/student/assignments': typeof AuthenticatedStudentAssignmentsRouteWithChildren
  '/_authenticated/student/classes': typeof AuthenticatedStudentClassesRoute
  '/_authenticated/teacher/announcements': typeof AuthenticatedTeacherAnnouncementsRoute
  '/_authenticated/teacher/assessments': typeof AuthenticatedTeacherAssessmentsRouteWithChildren
  '/_authenticated/teacher/classes': typeof AuthenticatedTeacherClassesRouteWithChildren
  '/_authenticated/teacher/events': typeof AuthenticatedTeacherEventsRoute
  '/_authenticated/teacher/meetings': typeof AuthenticatedTeacherMeetingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/parent/': typeof AuthenticatedParentIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/parent/children/$studentId': typeof AuthenticatedParentChildrenStudentIdRoute
  '/_authenticated/student/assignments/$assignmentId': typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
  '/_authenticated/teacher/assessments/$assessmentId': typeof AuthenticatedTeacherAssessmentsAssessmentIdRoute
  '/_authenticated/teacher/assignments/$assignmentId': typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
  '/_authenticated/teacher/classes/$classId': typeof AuthenticatedTeacherClassesClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/messages'
    | '/news'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/admin/academic-years'
    | '/admin/audit'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/fees'
    | '/admin/news'
    | '/admin/schools'
    | '/admin/subjects'
    | '/admin/terms'
    | '/admin/users'
    | '/parent/announcements'
    | '/parent/children'
    | '/parent/fees'
    | '/rankings/$classId'
    | '/settings/notifications'
    | '/student/assignments'
    | '/student/classes'
    | '/teacher/announcements'
    | '/teacher/assessments'
    | '/teacher/classes'
    | '/teacher/events'
    | '/teacher/meetings'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/parent/children/$studentId'
    | '/student/assignments/$assignmentId'
    | '/teacher/assessments/$assessmentId'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/classes/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/messages'
    | '/news'
    | '/admin/academic-years'
    | '/admin/audit'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/fees'
    | '/admin/news'
    | '/admin/schools'
    | '/admin/subjects'
    | '/admin/terms'
    | '/admin/users'
    | '/parent/announcements'
    | '/parent/children'
    | '/parent/fees'
    | '/rankings/$classId'
    | '/settings/notifications'
    | '/student/assignments'
    | '/student/classes'
    | '/teacher/announcements'
    | '/teacher/assessments'
    | '/teacher/classes'
    | '/teacher/events'
    | '/teacher/meetings'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/parent/children/$studentId'
    | '/student/assignments/$assignmentId'
    | '/teacher/assessments/$assessmentId'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/classes/$classId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/messages'
    | '/_authenticated/news'
    | '/_authenticated/parent'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/academic-years'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/schools'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/terms'
    | '/_authenticated/admin/users'
    | '/_authenticated/parent/announcements'
    | '/_authenticated/parent/children'
    | '/_authenticated/parent/fees'
    | '/_authenticated/rankings/$classId'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/student/assignments'
    | '/_authenticated/student/classes'
    | '/_authenticated/teacher/announcements'
    | '/_authenticated/teacher/assessments'
    | '/_authenticated/teacher/classes'
    | '/_authenticated/teacher/events'
    | '/_authenticated/teacher/meetings'
    | '/_authenticated/admin/'
    | '/_authenticated/parent/'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
    | '/_authenticated/parent/children/$studentId'
    | '/_authenticated/student/assignments/$assignmentId'
    | '/_authenticated/teacher/assessments/$assessmentId'
    | '/_authenticated/teacher/assignments/$assignmentId'
    | '/_authenticated/teacher/classes/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/academic-years': {
      id: '/_authenticated/admin/academic-years'
      path: '/academic-years'
      fullPath: '/admin/academic-years'
      preLoaderRoute: typeof AuthenticatedAdminAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schools': {
      id: '/_authenticated/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/terms': {
      id: '/_authenticated/admin/terms'
      path: '/terms'
      fullPath: '/admin/terms'
      preLoaderRoute: typeof AuthenticatedAdminTermsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/parent/': {
      id: '/_authenticated/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthenticatedParentIndexRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/announcements': {
      id: '/_authenticated/parent/announcements'
      path: '/announcements'
      fullPath: '/parent/announcements'
      preLoaderRoute: typeof AuthenticatedParentAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/children': {
      id: '/_authenticated/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof AuthenticatedParentChildrenRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/fees': {
      id: '/_authenticated/parent/fees'
      path: '/fees'
      fullPath: '/parent/fees'
      preLoaderRoute: typeof AuthenticatedParentFeesRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/rankings/$classId': {
      id: '/_authenticated/rankings/$classId'
      path: '/rankings/$classId'
      fullPath: '/rankings/$classId'
      preLoaderRoute: typeof AuthenticatedRankingsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/assignments': {
      id: '/_authenticated/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/classes': {
      id: '/_authenticated/student/classes'
      path: '/classes'
      fullPath: '/student/classes'
      preLoaderRoute: typeof AuthenticatedStudentClassesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/announcements': {
      id: '/_authenticated/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof AuthenticatedTeacherAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/assessments': {
      id: '/_authenticated/teacher/assessments'
      path: '/assessments'
      fullPath: '/teacher/assessments'
      preLoaderRoute: typeof AuthenticatedTeacherAssessmentsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/classes': {
      id: '/_authenticated/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof AuthenticatedTeacherClassesRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/events': {
      id: '/_authenticated/teacher/events'
      path: '/events'
      fullPath: '/teacher/events'
      preLoaderRoute: typeof AuthenticatedTeacherEventsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/meetings': {
      id: '/_authenticated/teacher/meetings'
      path: '/meetings'
      fullPath: '/teacher/meetings'
      preLoaderRoute: typeof AuthenticatedTeacherMeetingsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/parent/children/$studentId': {
      id: '/_authenticated/parent/children/$studentId'
      path: '/$studentId'
      fullPath: '/parent/children/$studentId'
      preLoaderRoute: typeof AuthenticatedParentChildrenStudentIdRouteImport
      parentRoute: typeof AuthenticatedParentChildrenRoute
    }
    '/_authenticated/student/assignments/$assignmentId': {
      id: '/_authenticated/student/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/student/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedStudentAssignmentsRoute
    }
    '/_authenticated/teacher/assessments/$assessmentId': {
      id: '/_authenticated/teacher/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/teacher/assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedTeacherAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedTeacherAssessmentsRoute
    }
    '/_authenticated/teacher/assignments/$assignmentId': {
      id: '/_authenticated/teacher/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/teacher/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedTeacherAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/classes/$classId': {
      id: '/_authenticated/teacher/classes/$classId'
      path: '/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof AuthenticatedTeacherClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedTeacherClassesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcademicYearsRoute: typeof AuthenticatedAdminAcademicYearsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminSchoolsRoute: typeof AuthenticatedAdminSchoolsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminTermsRoute: typeof AuthenticatedAdminTermsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcademicYearsRoute: AuthenticatedAdminAcademicYearsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminSchoolsRoute: AuthenticatedAdminSchoolsRoute,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminTermsRoute: AuthenticatedAdminTermsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedParentChildrenRouteChildren {
  AuthenticatedParentChildrenStudentIdRoute: typeof AuthenticatedParentChildrenStudentIdRoute
}

const AuthenticatedParentChildrenRouteChildren: AuthenticatedParentChildrenRouteChildren =
  {
    AuthenticatedParentChildrenStudentIdRoute:
      AuthenticatedParentChildrenStudentIdRoute,
  }

const AuthenticatedParentChildrenRouteWithChildren =
  AuthenticatedParentChildrenRoute._addFileChildren(
    AuthenticatedParentChildrenRouteChildren,
  )

interface AuthenticatedParentRouteChildren {
  AuthenticatedParentAnnouncementsRoute: typeof AuthenticatedParentAnnouncementsRoute
  AuthenticatedParentChildrenRoute: typeof AuthenticatedParentChildrenRouteWithChildren
  AuthenticatedParentFeesRoute: typeof AuthenticatedParentFeesRoute
  AuthenticatedParentIndexRoute: typeof AuthenticatedParentIndexRoute
}

const AuthenticatedParentRouteChildren: AuthenticatedParentRouteChildren = {
  AuthenticatedParentAnnouncementsRoute: AuthenticatedParentAnnouncementsRoute,
  AuthenticatedParentChildrenRoute:
    AuthenticatedParentChildrenRouteWithChildren,
  AuthenticatedParentFeesRoute: AuthenticatedParentFeesRoute,
  AuthenticatedParentIndexRoute: AuthenticatedParentIndexRoute,
}

const AuthenticatedParentRouteWithChildren =
  AuthenticatedParentRoute._addFileChildren(AuthenticatedParentRouteChildren)

interface AuthenticatedStudentAssignmentsRouteChildren {
  AuthenticatedStudentAssignmentsAssignmentIdRoute: typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
}

const AuthenticatedStudentAssignmentsRouteChildren: AuthenticatedStudentAssignmentsRouteChildren =
  {
    AuthenticatedStudentAssignmentsAssignmentIdRoute:
      AuthenticatedStudentAssignmentsAssignmentIdRoute,
  }

const AuthenticatedStudentAssignmentsRouteWithChildren =
  AuthenticatedStudentAssignmentsRoute._addFileChildren(
    AuthenticatedStudentAssignmentsRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentAssignmentsRoute: typeof AuthenticatedStudentAssignmentsRouteWithChildren
  AuthenticatedStudentClassesRoute: typeof AuthenticatedStudentClassesRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentAssignmentsRoute:
    AuthenticatedStudentAssignmentsRouteWithChildren,
  AuthenticatedStudentClassesRoute: AuthenticatedStudentClassesRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedTeacherAssessmentsRouteChildren {
  AuthenticatedTeacherAssessmentsAssessmentIdRoute: typeof AuthenticatedTeacherAssessmentsAssessmentIdRoute
}

const AuthenticatedTeacherAssessmentsRouteChildren: AuthenticatedTeacherAssessmentsRouteChildren =
  {
    AuthenticatedTeacherAssessmentsAssessmentIdRoute:
      AuthenticatedTeacherAssessmentsAssessmentIdRoute,
  }

const AuthenticatedTeacherAssessmentsRouteWithChildren =
  AuthenticatedTeacherAssessmentsRoute._addFileChildren(
    AuthenticatedTeacherAssessmentsRouteChildren,
  )

interface AuthenticatedTeacherClassesRouteChildren {
  AuthenticatedTeacherClassesClassIdRoute: typeof AuthenticatedTeacherClassesClassIdRoute
}

const AuthenticatedTeacherClassesRouteChildren: AuthenticatedTeacherClassesRouteChildren =
  {
    AuthenticatedTeacherClassesClassIdRoute:
      AuthenticatedTeacherClassesClassIdRoute,
  }

const AuthenticatedTeacherClassesRouteWithChildren =
  AuthenticatedTeacherClassesRoute._addFileChildren(
    AuthenticatedTeacherClassesRouteChildren,
  )

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherAnnouncementsRoute: typeof AuthenticatedTeacherAnnouncementsRoute
  AuthenticatedTeacherAssessmentsRoute: typeof AuthenticatedTeacherAssessmentsRouteWithChildren
  AuthenticatedTeacherClassesRoute: typeof AuthenticatedTeacherClassesRouteWithChildren
  AuthenticatedTeacherEventsRoute: typeof AuthenticatedTeacherEventsRoute
  AuthenticatedTeacherMeetingsRoute: typeof AuthenticatedTeacherMeetingsRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeacherAssignmentsAssignmentIdRoute: typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherAnnouncementsRoute:
    AuthenticatedTeacherAnnouncementsRoute,
  AuthenticatedTeacherAssessmentsRoute:
    AuthenticatedTeacherAssessmentsRouteWithChildren,
  AuthenticatedTeacherClassesRoute:
    AuthenticatedTeacherClassesRouteWithChildren,
  AuthenticatedTeacherEventsRoute: AuthenticatedTeacherEventsRoute,
  AuthenticatedTeacherMeetingsRoute: AuthenticatedTeacherMeetingsRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedTeacherAssignmentsAssignmentIdRoute:
    AuthenticatedTeacherAssignmentsAssignmentIdRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
  AuthenticatedRankingsClassIdRoute: typeof AuthenticatedRankingsClassIdRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedParentRoute: AuthenticatedParentRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
  AuthenticatedRankingsClassIdRoute: AuthenticatedRankingsClassIdRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
